"""Repository paths, database resolution, environment, and run namespaces.

This module exists because configuration used to live in five uncoordinated
places: argparse defaults with hardcoded relative paths, module-level
``DB = "prospects_snapshot.db"`` constants, bare ``sqlite3.connect("...")``
calls, environment variables read only inside ``deploy/``, and ~20 copies of
``REPO_ROOT = Path(__file__).resolve().parents[N]`` with an inconsistent N.
That drift produced at least one real bug (a trainer loading the previous
generation's hazard file because two modules disagreed about its name).

Scope boundary: this module owns *where things live* — paths, the database,
the environment, and run namespaces. It does NOT own the model's feature
contract. ``prospects.model.joint`` owns EVENTS, FEAT_COND, H_MAX,
PUBLISH_H, AGE_CENTER and YIP_CENTER, and remains the single source of truth
for them so feature ordering can never drift. Import them from there, not
from here.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

# --- repository root -------------------------------------------------------
# config.py sits at <repo>/prospects/config.py, so the root is one level up
# from the package. Every other module should import REPO_ROOT from here
# rather than recomputing parents[N].
REPO_ROOT = Path(__file__).resolve().parents[1]


# --- environment -----------------------------------------------------------
_ENV_LOADED = False


def load_env(path: Path | None = None, *, force: bool = False) -> None:
    """Load KEY=VALUE lines from .env into os.environ. Idempotent.

    Uses ``setdefault`` semantics: a variable already present in the
    environment WINS over the file. This is deliberate and load-bearing —
    ops/run_job.ps1 exports local path overrides (PROSPECT_DB, PRICES_DIR,
    ...) and those must not be clobbered by the checked-in .env defaults.
    Blank lines and ``#`` comments are ignored.
    """
    global _ENV_LOADED
    if _ENV_LOADED and not force:
        return
    env_path = path or (REPO_ROOT / ".env")
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())
    _ENV_LOADED = True


def env_path(var: str, default: Path) -> Path:
    """Read a path-valued environment variable, falling back to `default`."""
    load_env()
    raw = os.environ.get(var)
    return Path(raw) if raw else default


# --- databases -------------------------------------------------------------
# Two SQLite files, with genuinely different roles:
#
#   prospects.db          the LIVE database. deploy/daily_data.py appends
#                         current-season stats to it every night.
#   prospects_snapshot.db the MODELING database. Despite the name it is not
#                         frozen: deploy/weekly_score.py copies the live DB
#                         over it at the top of each weekly run. It exists so
#                         a multi-hour training run reads a stable file while
#                         the nightly pull keeps writing to the live one.
#
# That weekly copy is the ONE supported bridge between them. Modeling code
# should read MODEL_DB; ingestion and the deploy jobs should use LIVE_DB.
LIVE_DB = REPO_ROOT / "prospects.db"
MODEL_DB = REPO_ROOT / "prospects_snapshot.db"


def live_db() -> Path:
    """The live database, overridable via the PROSPECT_DB env var."""
    return env_path("PROSPECT_DB", LIVE_DB)


def model_db() -> Path:
    """The modeling database, overridable via the PROSPECT_MODEL_DB env var."""
    return env_path("PROSPECT_MODEL_DB", MODEL_DB)


# --- top-level directories -------------------------------------------------
RUNS_DIR = REPO_ROOT / "runs"          # one subdirectory per model run
ARCHIVE_DIR = REPO_ROOT / "archive"    # superseded runs and retired artifacts
REFERENCE_DIR = REPO_ROOT / "reference"  # hand-curated static inputs
LOGS_DIR = REPO_ROOT / "logs"          # scheduled-job logs
PRICES_DIR_DEFAULT = REPO_ROOT / "prices"  # daily eBay pulls

# Hand-curated reference inputs (checked in, not regenerated by the pipeline).
BASELINES_JSON = REFERENCE_DIR / "milb_baselines.json"      # league medians by level
BUYLIST_PRICES = REFERENCE_DIR / "prices" / "prices_bowman_chrome_auto_v13.csv"
BASEBALLCUBE_DIR = REFERENCE_DIR / "baseballcube"          # xref + rankings CSVs
# FanGraphs scouting-grade pipeline (scrape -> parse -> crosswalk -> build).
# SCOUTING_GRADES is the point-in-time output consumed at scoring time by
# features.grades; the rest of the directory is the regeneration workspace.
FANGRAPHS_DIR = REFERENCE_DIR / "fangraphs_board"
SCOUTING_GRADES = FANGRAPHS_DIR / "scouting_grades_pointintime.csv"

# Cross-run generated lookup consumed by both panel build and scoring: the
# PA/IP-weighted modal position per player (overrides prospects.primary_position,
# which has ~7k mislabels). Regenerated on data refresh, so it is not a
# per-run artifact — it lives beside the current run's models for convenience.
POSITION_LOOKUP = RUNS_DIR / "current" / "models" / "player_position_from_stats.csv"

# The live run is simply runs/current/. There is no pointer indirection: the
# weekly retrain overwrites runs/current/ in place, and superseded or
# experimental runs live under their own tag (runs/<tag>/ or, once retired,
# archive/runs/<tag>/). Set RUN_TAG in the environment to point a one-off
# command (a backtest, an A/B run) at a different run directory.
DEFAULT_TAG = "current"


# --- buy-list policy defaults ---------------------------------------------
# Policy knobs (what we choose to publish), as distinct from the model's
# feature contract in joint_cond. DEFAULT_THRESHOLD was previously hardcoded
# as a bare 0.60 in seven places across the buy-list builder and evaluators.
DEFAULT_THRESHOLD = 0.60
DEFAULT_DEBUT_HORIZON = 3


# --- run namespaces --------------------------------------------------------
@dataclass(frozen=True)
class RunPaths:
    """Every artifact directory belonging to one model run.

    A "run" is one pass of the pipeline under a tag (``prod``, ``v3``,
    ``partial``, ...). Previously a single run scattered its outputs across
    models/, results/scored/, results/buy_lists/, results/training/,
    evaluation/<tag>/ and scratch/v20b_oof_<tag>/, and the tag was applied by
    mutating module globals in five files independently. Now one run is one
    directory:

        runs/<tag>/
          models/      trained artifacts (hazards, joint XGB, calibrators)
          training/    fit/val longs, panel caches, pid lists
          scored/      snap scoring output
          buy_lists/   the published lists
          evaluation/  metric tables + generated README
          scratch/     regeneratable intermediates
          logs/        per-run training logs

    Because the directory carries the tag, the filenames inside it do not
    need to — `runs/v3/models/joint_xgb_oof.pkl`, not
    `models/joint_xgb_v2.0b_v3_oof.pkl`.
    """

    tag: str

    @property
    def root(self) -> Path:
        return RUNS_DIR / self.tag

    @property
    def models(self) -> Path:
        return self.root / "models"

    @property
    def training(self) -> Path:
        return self.root / "training"

    @property
    def scored(self) -> Path:
        return self.root / "scored"

    @property
    def buy_lists(self) -> Path:
        return self.root / "buy_lists"

    @property
    def evaluation(self) -> Path:
        return self.root / "evaluation"

    @property
    def scratch(self) -> Path:
        return self.root / "scratch"

    @property
    def logs(self) -> Path:
        return self.root / "logs"

    # --- canonical artifact paths -----------------------------------------
    # Named accessors so every module references ONE filename per artifact.
    # These names carry no version tag: the run directory already does. The
    # comment on each records the pre-refactor filename it replaces.
    @property
    def hazards_landmark(self) -> Path:      # event_classifiers_v1.18b_landmark_prod.pkl
        """Stage-A landmark hazards (80%-panel, the downstream's upstream)."""
        return self.models / "hazards_landmark.pkl"

    @property
    def hazards(self) -> Path:               # event_classifiers_v2.0b(_v3)_prod.pkl
        """Production hazards, trained on the full panel."""
        return self.models / "hazards.pkl"

    @property
    def lasso_logits(self) -> Path:          # lasso_logits_v1.18b_prod.pkl
        """Stage-A L1 bundle (feeds the p_debut_lasso timing feature)."""
        return self.models / "lasso_logits.pkl"

    @property
    def timing_stage_a(self) -> Path:        # time_to_debut_v1.18b_prod.pkl
        """Stage-A time-to-debut (fit alongside the L1 bundle)."""
        return self.models / "timing_stage_a.pkl"

    @property
    def timing(self) -> Path:                # time_to_debut_v2.0b_prod.pkl
        """Production time-to-debut (retrained on the v2.0b hazards)."""
        return self.models / "timing.pkl"

    @property
    def joint_xgb(self) -> Path:             # joint_xgb_v2.0b(_v3)_oof.pkl
        """The conditional joint XGB — the buy-list scoring head."""
        return self.models / "joint_xgb.pkl"

    @property
    def joint_xgb_prod(self) -> Path:        # joint_xgb_v2.0b_prod.pkl
        """Prod joint XGB written by the weekly retrain (in-sample hazards)."""
        return self.models / "joint_xgb_prod.pkl"

    @property
    def calibrators(self) -> Path:           # prob_calibrators_v2.0b(_v3).pkl
        """Per-(event, horizon) isotonic probability calibrators."""
        return self.models / "calibrators.pkl"

    def yip_thresholds(self, pct: int) -> Path:  # yip_thresholds_*_p{60,70}_h3.json
        """Per-yip precision-calibrated debut-probability cutoffs."""
        return self.models / f"yip_thresholds_p{pct}.json"

    # training intermediates
    @property
    def landmark_panel(self) -> Path:        # landmark_panel_v1.18b.npz
        return self.training / "landmark_panel.npz"

    @property
    def fit_long(self) -> Path:              # v1.18b_landmark_fit_long.csv
        return self.training / "fit_long.csv"

    @property
    def val_long(self) -> Path:              # v1.18b_landmark_val_long.csv
        return self.training / "val_long.csv"

    @property
    def all_long(self) -> Path:              # v1.18b_landmark_all_long.csv
        return self.training / "all_long.csv"

    @property
    def oof_stacked_long(self) -> Path:      # v2.0b(_v3)_oof_stacked_long.csv
        return self.training / "oof_stacked_long.csv"

    @property
    def oof_val_long(self) -> Path:          # v2.0b(_v3)_oof_val_long.csv
        return self.training / "oof_val_long.csv"

    @property
    def fit_pids(self) -> Path:              # v17_prod_fit_pids.txt
        return self.training / "fit_pids.txt"

    @property
    def val_pids(self) -> Path:              # v17_prod_val_pids.txt
        return self.training / "val_pids.txt"

    # scored + published
    def snap_long(self, season: int) -> Path:  # snap2026_v1.18b_landmark_long.csv
        return self.scored / f"snap{season}_long.csv"

    @property
    def buy_list_all(self) -> Path:          # buy_list_v2.0b_ALL_SCORED.csv
        return self.buy_lists / "all_scored.csv"

    @property
    def buy_list_final(self) -> Path:        # buy_list_v2.0b_FINAL.csv
        return self.buy_lists / "final.csv"

    def mkdirs(self) -> RunPaths:
        """Create every subdirectory. Returns self so it can be chained."""
        for d in (self.models, self.training, self.scored, self.buy_lists,
                  self.evaluation, self.scratch, self.logs):
            d.mkdir(parents=True, exist_ok=True)
        return self

    @classmethod
    def current(cls) -> RunPaths:
        """The run the pipeline reads and writes by default: runs/current/,
        unless RUN_TAG overrides it for a one-off command."""
        return cls(current_tag())


def current_tag() -> str:
    """Tag of the current run (env RUN_TAG, else DEFAULT_TAG = 'current')."""
    load_env()
    tag = os.environ.get("RUN_TAG")
    return tag.strip() if tag else DEFAULT_TAG


def run(tag: str | None = None) -> RunPaths:
    """RunPaths for `tag`, or for the current run when tag is None.

    The standard way for a script to accept a --tag flag:

        ap.add_argument("--tag", default=None)
        paths = config.run(args.tag)
    """
    return RunPaths(tag) if tag else RunPaths.current()
