"""
prospects/model/train/make_split.py
===================================

Build the fit/val holdout the training + evaluation pipelines read
(``runs/<tag>/training/{fit_pids,val_pids}.txt``).

This split had been a lost one-off: created once on the main machine, never
committed, and regenerated by no code — so ``oof`` (and everything downstream)
hard-failed on a missing ``val_pids.txt``. This module makes it a repeatable,
deterministic step.

What the split is
-----------------
A player-level holdout over the modeling universe: drafted on or before
``--max-draft-year`` (default 2020) with a career outcome and at least one
MiLB season (i.e. panel-eligible). ``--val-frac`` (default 0.15) of those
players are held out as ``val``; the rest are ``fit``. ``oof`` right-censors the
val cohort away from every fold, then scores it honestly; ``prod`` trains the
joint XGB on the resulting out-of-fold longs.

Because the prospects table is deduped to one row per mlbam before this runs,
splitting by ``player_id`` is equivalent to splitting by real player — no
re-drafted player can land in both fit and val.

Usage
-----
    python -m prospects.model.train.make_split                 # seed=42, 15%
    python -m prospects.model.train.make_split --val-frac 0.2
    python -m prospects.model.train.make_split --tag cand      # writes runs/cand/
"""

from __future__ import annotations

import argparse
import random
import sqlite3
from pathlib import Path

from prospects import config
from prospects.config import REPO_ROOT


def eligible_pids(db_path: str, max_draft_year: int) -> list[str]:
    """Panel-eligible modeling universe: drafted <= max_draft_year, with an
    outcome label and at least one MiLB season. Sorted for determinism."""
    con = sqlite3.connect(db_path)
    rows = con.execute(
        """
        SELECT DISTINCT p.player_id
        FROM prospects p
        JOIN career_outcomes o ON o.player_id = p.player_id
        JOIN season_stats    s ON s.player_id = p.player_id
        WHERE p.draft_year IS NOT NULL AND p.draft_year <= ?
        """,
        (max_draft_year,),
    ).fetchall()
    con.close()
    return sorted(r[0] for r in rows)


def make_split(
    db_path: str,
    val_frac: float = 0.15,
    seed: int = 42,
    max_draft_year: int = 2020,
    tag: str | None = None,
) -> dict:
    """Write fit_pids.txt + val_pids.txt for the given run tag. Deterministic in
    (universe, seed): same DB + seed => identical split. Returns a stats dict."""
    run = config.run(tag)
    run.training.mkdir(parents=True, exist_ok=True)

    pids = eligible_pids(db_path, max_draft_year)
    if not pids:
        raise SystemExit(
            f"No panel-eligible pids in {db_path} (drafted<= {max_draft_year} "
            f"with outcome + season_stats). Did the pull + dedup run?")

    rng = random.Random(seed)
    shuffled = pids[:]           # already sorted -> deterministic starting order
    rng.shuffle(shuffled)
    n_val = round(len(shuffled) * val_frac)
    val = set(shuffled[:n_val])
    fit = [p for p in pids if p not in val]           # keep sorted order
    val_sorted = [p for p in pids if p in val]

    run.val_pids.write_text("\n".join(val_sorted) + "\n")
    run.fit_pids.write_text("\n".join(fit) + "\n")

    stats = {"universe": len(pids), "val": len(val_sorted), "fit": len(fit),
             "val_frac": round(len(val_sorted) / len(pids), 4),
             "seed": seed, "max_draft_year": max_draft_year}
    print(f"[make_split] universe={stats['universe']:,}  "
          f"val={stats['val']:,} ({100*stats['val_frac']:.1f}%)  "
          f"fit={stats['fit']:,}  seed={seed}")
    print(f"[make_split] wrote {run.val_pids}")
    print(f"[make_split] wrote {run.fit_pids}")
    return stats


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=str(REPO_ROOT / "prospects_snapshot.db"))
    ap.add_argument("--val-frac", type=float, default=0.15)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--max-draft-year", type=int, default=2020)
    ap.add_argument("--tag", default=None, help="Run tag (default: current)")
    args = ap.parse_args()
    make_split(args.db, val_frac=args.val_frac, seed=args.seed,
               max_draft_year=args.max_draft_year, tag=args.tag)


if __name__ == "__main__":
    main()
